Running Move unit tests
[ FAIL    ] 0x1::M::fail
[ FAIL    ] 0x1::M::fail_with_code
0x1::M::fail
Output: Ok(ChangeSet { accounts: {} })
0x1::M::fail_with_code
Output: Ok(ChangeSet { accounts: {} })

Test failures:

Failures in 0x1::M:

┌── fail ──────
│ Test did not fail as expected
└──────────────────


┌── fail_with_code ──────
│ Test did not fail as expected
└──────────────────

Test result: FAILED. Total tests: 2; passed: 0; failed: 2
